

hours_temps = {
    0: {'current_hour': 'ноль', 'future_hour': 'первого', 'future_hour_std': 'час'},
    1: {'current_hour': 'час', 'future_hour': 'второго', 'future_hour_std': 'два'},
    2: {'current_hour': 'два', 'future_hour': 'третьего', 'future_hour_std': 'три'},
    3: {'current_hour': 'три', 'future_hour': 'четвёртого', 'future_hour_std': 'четыре'},
    4: {'current_hour': 'четыре', 'future_hour': 'пятого', 'future_hour_std': 'пять'},
    5: {'current_hour': 'пять', 'future_hour': 'шестого', 'future_hour_std': 'шесть'},
    6: {'current_hour': 'шесть', 'future_hour': 'седьмого', 'future_hour_std': 'семь'},
    7: {'current_hour': 'семь', 'future_hour': 'восьмого', 'future_hour_std': 'восемь'},
    8: {'current_hour': 'восемь', 'future_hour': 'девятого', 'future_hour_std': 'девять'},
    9: {'current_hour': 'девять', 'future_hour': 'десятого', 'future_hour_std': 'десять'},
    10: {'current_hour': 'десять', 'future_hour': 'одиннадцатого', 'future_hour_std': 'одиннадцать'},
    11: {'current_hour': 'одиннадцать', 'future_hour': 'двенадцатого', 'future_hour_std': 'полдень'},
    12: {'current_hour': 'двенадцать', 'future_hour': 'первого', 'future_hour_std': 'час'},
    13: {'current_hour': 'час', 'future_hour': 'второго', 'future_hour_std': 'два'},
    14: {'current_hour': 'два', 'future_hour': 'третьего', 'future_hour_std': 'три'},
    15: {'current_hour': 'три', 'future_hour': 'четвёртого', 'future_hour_std': 'четыре'},
    16: {'current_hour': 'четыре', 'future_hour': 'пятого', 'future_hour_std': 'пять'},
    17: {'current_hour': 'пять', 'future_hour': 'шестого', 'future_hour_std': 'шесть'},
    18: {'current_hour': 'шесть', 'future_hour': 'седьмого', 'future_hour_std': 'семь'},
    19: {'current_hour': 'семь', 'future_hour': 'восьмого', 'future_hour_std': 'восемь'},
    20: {'current_hour': 'восемь', 'future_hour': 'девятого', 'future_hour_std': 'девять'},
    21: {'current_hour': 'девять', 'future_hour': 'десятого', 'future_hour_std': 'десять'},
    22: {'current_hour': 'десять', 'future_hour': 'одиннадцатого', 'future_hour_std': 'одиннадцать'},
    23: {'current_hour': 'одиннадцать', 'future_hour': 'до полуночи', 'future_hour_std': 'полночь'}
}


base_temps = {
    0: ["$current_hour", "$current_hour ровно"],
    1: ["одна минута $future_hour", "$current_hour часов одна минута", "без пятидесяти девяти $future_hour_std"],
    2: ["две минуты $future_hour", "$current_hour часов две минуты"],
    3: ["три минуты $future_hour", "$current_hour часов три минуты"],
    4: ["четыре минуты $future_hour", "$current_hour часов четыре минуты"],
    5: ["пять минут $future_hour", "$current_hour часов пять минут"],
    6: ["шесть минут $future_hour", "$current_hour часов шесть минут"],
    7: ["семь минут $future_hour", "$current_hour часов семь минут"],
    8: ["восемь минут $future_hour", "$current_hour часов восемь минут"],
    9: ["девять минут $future_hour", "$current_hour часов девять минут"],
    10: ["десять минут $future_hour", "$current_hour часов десять минут", "$current_hour десять"],
    11: ["одиннадцать минут $future_hour", "$current_hour часов одиннадцать минут"],
    12: ["двенадцать минут $future_hour", "$current_hour часов двенадцать минут"],
    13: ["тринадцать минут $future_hour", "$current_hour часов тринадцать минут"],
    14: ["четырнадцать минут $future_hour", "$current_hour часов четырнадцать минут"],
    15: ["пятнадцать минут $future_hour", "$current_hour часов пятнадцать минут",
         "четверть $future_hour", "$current_hour с четвертью"],
    16: ["шестнадцать минут $future_hour", "$current_hour часов шестнадцать минут"],
    17: ["семнадцать минут $future_hour", "$current_hour часов семнадцать минут"],
    18: ["восемнадцать минут $future_hour", "$current_hour часов восемнадцать минут"],
    19: ["девятнадцать минут $future_hour", "$current_hour часов девятнадцать минут"],
    20: ["двадцать минут $future_hour", "$current_hour часов двадцать минут", "$current_hour двадцать"],
    21: ["двадцать одна минута $future_hour", "$current_hour часов двадцать одна минута"],
    22: ["двадцать две минуты $future_hour", "$current_hour часов двадцать две минуты"],
    23: ["двадцать три минуты $future_hour", "$current_hour часов двадцать три минуты"],
    24: ["двадцать четыре минуты $future_hour", "$current_hour часов двадцать четыре минуты"],
    25: ["двадцать пять минут $future_hour", "$current_hour часов двадцать пять минут", "без пять пол $future_hour"],
    26: ["двадцать шесть минут $future_hour", "$current_hour часов двадцать шесть минут"],
    27: ["двадцать семь минут $future_hour", "$current_hour часов двадцать семь минут"],
    28: ["двадцать восемь минут $future_hour", "$current_hour часов двадцать восемь минут"],
    29: ["двадцать девять минут $future_hour", "$current_hour часов двадцать девять минут"],
    30: ["половина $future_hour", "$current_hour часов тридцать минут", "$current_hour тридцать"],
    31: ["тридцать одна минута $future_hour", "$current_hour часов тридцать одна минута"],
    32: ["тридцать две минуты $future_hour", "$current_hour часов тридцать две минуты"],
    33: ["тридцать три минуты $future_hour", "$current_hour часов тридцать три минуты"],
    34: ["тридцать четыре минуты $future_hour", "$current_hour часов тридцать четыре минуты"],
    35: ["тридцать пять минут $future_hour", "$current_hour часов тридцать пять минут"],
    36: ["тридцать шесть минут $future_hour", "$current_hour часов тридцать шесть минут"],
    37: ["тридцать семь минут $future_hour", "$current_hour часов тридцать семь минут"],
    38: ["тридцать восемь минут $future_hour", "$current_hour часов тридцать восемь минут"],
    39: ["тридцать девять минут $future_hour", "$current_hour часов тридцать девять минут"],
    40: ["$current_hour часов сорок минут", "без двадцати $future_hour_std", "$current_hour сорок"],
    41: ["сорок одна минута $future_hour", "$current_hour часов сорок одна минута"],
    42: ["сорок две минуты $future_hour", "$current_hour часов сорок две минуты"],
    43: ["сорок три минуты $future_hour", "$current_hour часов сорок три минуты"],
    44: ["сорок четыре минуты $future_hour", "$current_hour часов сорок четыре минуты"],
    45: ["$current_hour часов сорок пять минут", "без пятнадцати $future_hour_std", "$current_hour сорок пять"],
    46: ["сорок шесть минут $future_hour", "$current_hour часов сорок шесть минут"],
    47: ["сорок семь минут $future_hour", "$current_hour часов сорок семь минут"],
    48: ["сорок восемь минут $future_hour", "$current_hour часов сорок восемь минут"],
    49: ["сорок девять минут $future_hour", "$current_hour часов сорок девять минут"],
    50: ["пятьдесят минут $future_hour", "без десяти $future_hour_std", "$current_hour часов пятьдесят минут"],
    51: ["пятьдесят одна минута $future_hour", "$current_hour часов пятьдесят одна минута"],
    52: ["пятьдесят две минуты $future_hour", "$current_hour часов пятьдесят две минуты"],
    53: ["пятьдесят три минуты $future_hour", "$current_hour часов пятьдесят три минуты"],
    54: ["пятьдесят четыре минуты $future_hour", "$current_hour часов пятьдесят четыре минуты"],
    55: ["$current_hour часов пятьдесят пять минут", "без пяти $future_hour_std", "$current_hour сорок пять"],
    56: ["пятьдесят шесть минут $future_hour", "$current_hour часов пятьдесят шесть минут"],
    57: ["пятьдесят семь минут $future_hour", "$current_hour часов пятьдесят семь минут"],
    58: ["пятьдесят восемь минут $future_hour", "$current_hour часов пятьдесят восемь минут"],
    59: ["пятьдесят девять минут $future_hour", "$current_hour часов пятьдесят девять минут",
         "без минуты $future_hour_std"]
}
