hours_temps = {
    0: {"current_hour_std": "дванадцята", "current_hour_first": "дванадцятій", "future_hour_first": "першу", "future_hour_std": "перша", "future_hour_second": "першої"},
    1: {"current_hour_std": "перша", "current_hour_first": "першій", "future_hour_first": "другу", "future_hour_std": "друга", "future_hour_second": "другої"},
    2: {"current_hour_std": "друга", "current_hour_first": "другій", "future_hour_first": "третю", "future_hour_std": "третя", "future_hour_second": "третьої"},
    3: {"current_hour_std": "третя", "current_hour_first": "третій", "future_hour_first": "четверту", "future_hour_std": "четверта", "future_hour_second": "четвертої"},
    4: {"current_hour_std": "четверта", "current_hour_first": "четвертій", "future_hour_first": "п'яту", "future_hour_std": "п'ята", "future_hour_second": "п'ятої"},
    5: {"current_hour_std": "п'ята", "current_hour_first": "п'ятій", "future_hour_first": "шосту", "future_hour_std": "шоста", "future_hour_second": "шостої"},
    6: {"current_hour_std": "шоста", "current_hour_first": "шостій", "future_hour_first": "сьому", "future_hour_std": "сьома", "future_hour_second": "сьомої"},
    7: {"current_hour_std": "сьома", "current_hour_first": "сьомій", "future_hour_first": "восьму", "future_hour_std": "восьма", "future_hour_second": "восьмої"},
    8: {"current_hour_std": "восьма", "current_hour_first": "восьмій", "future_hour_first": "дев'яту", "future_hour_std": "дев'ята", "future_hour_second": "дев'ятої"},
    9: {"current_hour_std": "дев'ята", "current_hour_first": "дев'ятій", "future_hour_first": "десяту", "future_hour_std": "десята", "future_hour_second": "десятої"},
    10: {"current_hour_std": "десята", "current_hour_first": "десятій", "future_hour_first": "одинадцяту", "future_hour_std": "одинадцята", "future_hour_second": "одинадцятої"},
    11: {"current_hour_std": "одинадцята", "current_hour_first": "одинадцятій", "future_hour_first": "дванадцяту", "future_hour_std": "дванадцята", "future_hour_second": "дванадцятої"},
    12: {"current_hour_std": "дванадцята", "current_hour_first": "дванадцятій", "future_hour_first": "першу", "future_hour_std": "перша", "future_hour_second": "першої"},
    13: {"current_hour_std": "перша", "current_hour_first": "першій", "future_hour_first": "другу", "future_hour_std": "друга", "future_hour_second": "другої"},
    14: {"current_hour_std": "друга", "current_hour_first": "другій", "future_hour_first": "третю", "future_hour_std": "третя", "future_hour_second": "третьої"},
    15: {"current_hour_std": "третя", "current_hour_first": "третій", "future_hour_first": "четверту", "future_hour_std": "четверта", "future_hour_second": "четвертої"},
    16: {"current_hour_std": "четверта", "current_hour_first": "четвертій", "future_hour_first": "п'яту", "future_hour_std": "п'ята", "future_hour_second": "п'ятої"},
    17: {"current_hour_std": "п'ята", "current_hour_first": "п'ятій", "future_hour_first": "шосту", "future_hour_std": "шоста", "future_hour_second": "шостої"},
    18: {"current_hour_std": "шоста", "current_hour_first": "шостій", "future_hour_first": "сьому", "future_hour_std": "сьома", "future_hour_second": "сьомої"},
    19: {"current_hour_std": "сьома", "current_hour_first": "сьомій", "future_hour_first": "восьму", "future_hour_std": "восьма", "future_hour_second": "восьмої"},
    20: {"current_hour_std": "восьма", "current_hour_first": "восьмій", "future_hour_first": "дев'яту", "future_hour_std": "дев'ята", "future_hour_second": "дев'ятої"},
    21: {"current_hour_std": "дев'ята", "current_hour_first": "дев'ятій", "future_hour_first": "десяту", "future_hour_std": "десята", "future_hour_second": "десятої"},
    22: {"current_hour_std": "десята", "current_hour_first": "десятій", "future_hour_first": "одинадцяту", "future_hour_std": "одинадцята", "future_hour_second": "одинадцятої"},
    23: {"current_hour_std": "одинадцята", "current_hour_first": "одинадцятій", "future_hour_first": "дванадцяту", "future_hour_std": "дванадцята", "future_hour_second": "дванадцятої"},
}


minutes_temps = {
    0: ["$current_hour_std година рівно", "рівно $current_hour_std година"],
    1: ["$current_hour_std година одна хвилина", "хвилина по $current_hour_first", "хвилина на $future_hour_first"],
    2: ["$current_hour_std година дві хвилини", "дві хвилини по $current_hour_first", "дві хвилини на $future_hour_first"],
    3: ["$current_hour_std година три хвилини", "три хвилини по $current_hour_first", "три хвилини на $future_hour_first"],
    4: ["$current_hour_std година чотири хвилини", "чотири хвилини по $current_hour_first", "чотири хвилини на $future_hour_first"],
    5: ["$current_hour_std година п'ять хвилин", "п'ять хвилин по $current_hour_first", "п'ять хвилин на $future_hour_first"],
    6: ["$current_hour_std година шість хвилин", "шість хвилин по $current_hour_first", "шість хвилин на $future_hour_first"],
    7: ["$current_hour_std година сім хвилин", "сім хвилин по $current_hour_first", "сім хвилин на $future_hour_first"],
    8: ["$current_hour_std година вісім хвилин", "вісім хвилин по $current_hour_first", "вісім хвилин на $future_hour_first"],
    9: ["$current_hour_std година дев'ять хвилин", "дев'ять хвилин по $current_hour_first", "дев'ять хвилин на $future_hour_first"],
    10: ["$current_hour_std година десять хвилин", "десять хвилин по $current_hour_first", "десять хвилин на $future_hour_first"],
    11: ["$current_hour_std година одинадцять хвилин", "одинадцять хвилин по $current_hour_first", "одинадцять хвилин на $future_hour_first"],
    12: ["$current_hour_std година дванадцять хвилин", "дванадцять хвилин по $current_hour_first", "дванадцять хвилин на $future_hour_first"],
    13: ["$current_hour_std година тринадцять хвилин", "тринадцять хвилин по $current_hour_first", "тринадцять хвилин на $future_hour_first"],
    14: ["$current_hour_std година чотирнадцять хвилин", "чотирнадцять хвилин по $current_hour_first", "чотирнадцять хвилин на $future_hour_first"],
    15: ["$current_hour_std година п'ятнадцять хвилина", "п'ятнадцять хвилин по $current_hour_first", "п'ятнадцять хвилин на $future_hour_first",
         "чверть по $current_hour_first", "чверть на $future_hour_first"],
    16: ["$current_hour_std година шістнадцять хвилин", "шістнадцять хвилин по $current_hour_first", "шістнадцять хвилин на $future_hour_first"],
    17: ["$current_hour_std година сімнадцять хвилин", "сімнадцять хвилин по $current_hour_first", "сімнадцять хвилин на $future_hour_first"],
    18: ["$current_hour_std година вісімнадцять хвилин", "вісімнадцять хвилин по $current_hour_first", "вісімнадцять хвилин на $future_hour_first"],
    19: ["$current_hour_std година дев'ятнадцять хвилин", "дев'ятнадцять хвилин по $current_hour_first", "дев'ятнадцять хвилин на $future_hour_first"],
    20: ["$current_hour_std година двадцять хвилин", "двадцять хвилин по $current_hour_first", "двадцять хвилин на $future_hour_first"],
    21: ["$current_hour_std година двадцять одна хвилина", "двадцять одна хвилина по $current_hour_first", "двадцять одна хвилина на $future_hour_first"],
    22: ["$current_hour_std година двадцять дві хвилини", "двадцять дві хвилини по $current_hour_first", "двадцять дві хвилини на $future_hour_first"],
    23: ["$current_hour_std година двадцять три хвилини", "двадцять три хвилини по $current_hour_first", "двадцять три хвилини на $future_hour_first"],
    24: ["$current_hour_std година двадцять чотири хвилини", "двадцять чотири хвилини по $current_hour_first", "двадцять чотири хвилини на $future_hour_first"],
    25: ["$current_hour_std година двадцять п'ять хвилин", "двадцять п'ять хвилин по $current_hour_first", "двадцять п'ять хвилин на $future_hour_first"],
    26: ["$current_hour_std година двадцять шість хвилин", "двадцять шість хвилин по $current_hour_first", "двадцять шість хвилин на $future_hour_first"],
    27: ["$current_hour_std година двадцять сім хвилин", "двадцять сім хвилин по $current_hour_first", "двадцять сім хвилин на $future_hour_first"],
    28: ["$current_hour_std година двадцять вісім хвилин", "двадцять вісім хвилин по $current_hour_first", "двадцять вісім хвилин на $future_hour_first"],
    29: ["$current_hour_std година двадцять дев'ять хвилин", "двадцять дев'ять хвилин по $current_hour_first", "двадцять дев'ять хвилин на $future_hour_first"],
    30: ["$current_hour_std година тридцать хвилин", "пів на $future_hour_first"],
    31: ["$current_hour_std година тридцять одна хвилина", "за двадцять дев'ять хвилин $future_hour_std", "двадцять дев'ять хвилин до $future_hour_second"],
    32: ["$current_hour_std година тридцять дві хвилини", "за двадцять вісім хвилин $future_hour_std", "двадцять вісім хвилин до $future_hour_second"],
    33: ["$current_hour_std година тридцять три хвилини", "за двадцять сім хвилин $future_hour_std", "двадцять сім хвилин до $future_hour_second"],
    34: ["$current_hour_std година тридцять чотири хвилини", "за двадцять шість хвилин $future_hour_std", "двадцять шість хвилин до $future_hour_second"],
    35: ["$current_hour_std година тридцять п'ять хвилин", "за двадцять п'ять хвилин $future_hour_std", "двадцять п'ять хвилин до $future_hour_second"],
    36: ["$current_hour_std година тридцять шість хвилин", "за двадцять чотири хвилини $future_hour_std", "двадцять чотири хвилини до $future_hour_second"],
    37: ["$current_hour_std година тридцять сім хвилин", "за двадцять три хвилини $future_hour_std", "двадцять три хвилини до $future_hour_second"],
    38: ["$current_hour_std година тридцять вісім хвилин", "за двадцять дві хвилини $future_hour_std", "двадцять дві хвилини до $future_hour_second"],
    39: ["$current_hour_std година тридцять дев'ять хвилин", "за двадцять одну хвилину $future_hour_std", "двадцять одна хвилина до $future_hour_second"],
    40: ["$current_hour_std година сорок хвилин", "за двадцять хвилин $future_hour_std", "двадцять хвилин до $future_hour_second"],
    41: ["$current_hour_std година сорок одна хвилина", "за дев'ятнадцять хвилин $future_hour_std", "дев'ятнадцять хвилин до $future_hour_second"], 
    42: ["$current_hour_std година сорок дві хвилини", "за вісімнадцять хвилин $future_hour_std", "вісімнадцять хвилин до $future_hour_second"],
    43: ["$current_hour_std година сорок три хвилини", "за сімнадцять хвилин $future_hour_std", "сімнадцять хвилин до $future_hour_second"],
    44: ["$current_hour_std година сорок чотири хвилини", "за шістнадцять хвилин $future_hour_std", "шістнадцять хвилин до $future_hour_second"],
    45: ["$current_hour_std година сорок п'ять хвилин", "за п'ятнадцять хвилин $future_hour_std", "п'ятнадцять хвилин до $future_hour_second",
         "за чверть $future_hour_std", "чверть до $future_hour_second"],
    46: ["$current_hour_std година сорок шість хвилин", "за чотирнадцять хвилин $future_hour_std", "чотирнадцять хвилин до $future_hour_second"],
    47: ["$current_hour_std година сорок сім хвилин", "за тринадцять хвилин $future_hour_std", "тринадцять хвилин до $future_hour_second"],
    48: ["$current_hour_std година сорок вісім хвилин", "за дванадцять хвилин $future_hour_std", "дванадцять хвилин до $future_hour_second"],
    49: ["$current_hour_std година сорок дев'ять хвилин", "за одинадцять хвилин $future_hour_std", "одинадцять хвилин до $future_hour_second"],
    50: ["$current_hour_std година п'ятдесят хвилин", "за десять хвилин $future_hour_std", "десять хвилин до $future_hour_second"],
    51: ["$current_hour_std година п'ятдесят одна хвилина", "за дев'ять хвилин $future_hour_std", "дев'ять хвилин до $future_hour_second"],
    52: ["$current_hour_std година п'ятдесят дві хвилини", "за вісім хвилин $future_hour_std", "вісім хвилин до $future_hour_second"],
    53: ["$current_hour_std година п'ятдесят три хвилини", "за сім хвилин $future_hour_std", "сім хвилин до $future_hour_second"],
    54: ["$current_hour_std година п'ятдесят чотири хвилини", "за шість хвилин $future_hour_std", "шість хвилин до $future_hour_second"],
    55: ["$current_hour_std година п'ятдесят п'ять хвилин", "за п'ять хвилин $future_hour_std", "п'ять хвилин до $future_hour_second"],
    56: ["$current_hour_std година п'ятдесят шість хвилин", "за чотири хвилини $future_hour_std", "чотири хвилини до $future_hour_second"],
    57: ["$current_hour_std година п'ятдесят сім хвилин", "за три хвилини $future_hour_std", "три хвилини до $future_hour_second"],
    58: ["$current_hour_std година п'ятдесят вісім хвилин", "за дві хвилини $future_hour_std", "дві хвилини до $future_hour_second"],
    59: ["$current_hour_std година п'ятдесят дев'ять хвилин", "за хвилину $future_hour_std", "хвилина до $future_hour_second"],
}